# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Code-Splice
version:      0.01
version_from: lib/Code/Splice.pm
installdirs:  site
requires:
    B::Generate:                   0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
